#!/bin/bash

# Clumsy, but workable
base=`php -r "echo realpath('.');"`
while [ ! -d $base/.git ]; do
	base=`php -r "echo realpath('../$base');"`
	if [ base=/ ]; then
		break;
	fi
done

gitconfig=$base/.git/config

# gitsvn detection
if [ "`grep '\[svn-remote' $gitconfig`" = "" ]; then
	gitsvn=0
else
	gitsvn=1
fi

case "$1" in
type)
	if [ $gitsvn = 1 ]; then
		echo "This is a git-svn project"
	else
		echo "This is a regular git project (not git-svn)"
	fi

	;;

pull)
	didstash=0
	if [ "`git diff`" != "" -o "`git diff --cached`" != "" ]; then
		echo "> git stash"
		git stash
		didstash=1
	fi

	if [ $gitsvn = 1 ]; then
		echo "> git svn rebase"
		git svn rebase
		if [ $? != 0 ]; then
			echo "It looks like there was a conflict when rebasing against the upstream changes.
You will need to resolve this commit and then run '$0 resolved' or '$0 skip'"
			exit 1
		fi

	else
		echo "> git pull --rebase"
		git pull --rebase

		if [ $? != 0 ]; then
			echo "It looks like there was a conflict when rebasing against the upstream changes.
You will need to resolve this commit and then run '$0 resolved' or '$0 skip'"
			exit 1
		fi
	fi

	if [ $didstash = 1 ]; then
		echo "> git stash pop"
		git stash pop
	fi

	;;
	
push)
	didstash=0
	if [ "`git diff`" != "" -o "`git diff --cached`" != "" ]; then
		echo "> git stash"
		git stash
		didstash=1
	fi

	if [ $gitsvn = 1 ]; then
		echo "git svn rebase"
		git svn rebase
		if [ $? != 0 ]; then
			echo "It looks like there was a conflict when rebasing against the upstream changes.
You will need to resolve this commit and then run '$0 resolved' or '$0 skip'"
			exit 1
		fi
		git svn dcommit

	else
		echo "> git pull --rebase"
		git pull --rebase

		if [ $? != 0 ]; then
			echo "It looks like there was a conflict when rebasing against the upstream changes.
You will need to resolve this commit and then run '$0 resolved' or '$0 skip'"
			exit 1
		fi

		echo "> git push --tags"
		git push --tags
	fi

	if [ $didstash = 1 ]; then
		echo "> git stash pop"
		git stash pop
	fi

	;;
	
resolved)
	if [ "`git diff --cached`" = "" ]; then
		echo "There are no changes staged.
 - If you have forgotten to stage changes (with 'git add' or GitX)
 - If you have staged all the changes, and it so happens that there aren't any, run '$0 skip' instead"
		exit 1
	fi
	
	echo "> git rebase --continue"
	git rebase --continue
	if [ $? != 0 ]; then
		echo "It looks like there was a conflict when rebasing against the upstream changes.
You will need to resolve this commit and then run '$0 resolved' or '$0 skip'"
		exit 1
	fi

	;;

skip)
	echo "> git rebase --skip"
	git rebase --skip
	if [ $? != 0 ]; then
		echo "It looks like there was a conflict when rebasing against the upstream changes.
You will need to resolve this commit and then run '$0 resolved' or '$0 skip'"
		exit 1
	fi
	
	;;

# OK, THIS IS MORE ADVANCED THAN EASY

stashtobranch)
	if [ "$2" = "" ]; then
		echo "Usage: $0 stashtobranch (branch) (message)"
		exit 1
	fi
	
	if [ "`git diff`" = "" -a "`git diff --cached`" = "" ]; then
		echo "There's nothing to stash to a branch"
		exit 2
	fi

	currentbranch=`git branch | grep "*" | awk "{ print \\\$2 }"`

	echo "> git stash"
	git stash
	echo "> git checkout -b $2"
	git checkout -b $2
	if [ $? != 0 ]; then
		echo "Couldn't create branch, cancelling"
		echo "> git stash pop"
		git stash pop
		exit 1
	fi
	
	echo "> git stash pop"
	git stash pop
	echo "> git add ."
	git add .
	if [ "$3" = "" ]; then
		echo "> git commit"
		echo "> git commit -m \"Stashed work to temporary branch\""
		git commit -m "Stashed work to temporary branch"
	else
		echo "> git commit -m \"$3\""
		git commit -m "$3"
	fi
	echo "> git checkout $currentbranch"
	git checkout $currentbranch
	
	;;

*)
	echo "Usage:

	$0 type: Print the type of repository
	
	$0 pull: Pull changes from the central repository
	
	$0 push: Push changes to the central repository
	
	$0 resolved: Call this after resolving conflicts and staging the changes

	$0 skip: Call this to skip a conflicted changeset
"

	;;
esac